name: jarvis runner

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
  auto-repair:
    needs: checkout
    runs-on: self-hosted
    steps:
      - name: run jarvis action
        uses: BaeEB/jarvis-action@4_turbo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: jarvis_target
